/* Generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "adaptive-trivia",
  "name": "Trivia Elo",
  "supabaseUrl": "https://izyyaxovwwvjrladiumv.supabase.co",
  "supabaseAnonKey": "sb_publishable_nCqQWacYrOdTDGU9yspukA_jQvQoc9I",
  "aiProxy": "https://ai-proxy.goede-aeb.workers.dev",
  "google": false,
  "prompts": [
    {
      "say": "Only history questions for now",
      "does": "Switches the category and picks the next question."
    },
    {
      "say": "How am I doing in science?",
      "does": "Reads your category rating and accuracy."
    },
    {
      "say": "Add a question about the first moon landing",
      "does": "Writes, validates and adds a question to the bank."
    }
  ]
};
